version: '3'
services:
  shellcheck:
    build:
      context: ./
      dockerfile: Dockerfile.shellcheck
    volumes:
      - ./:/usr/local/src/bash-commons
    working_dir: /usr/local/src/bash-commons/.circleci
    command: ./shellcheck.sh
  bats_ubuntu1604:
    build:
      context: ./
      dockerfile: Dockerfile.ubuntu16.04.bats
    volumes:
      # Mount all the files so you have "hot reload" of all changes from the host
      - ./:/usr/local/src/bash-commons
    working_dir: /usr/local/src/bash-commons
    command: bats test
    # Necessary so we can run a mock EC2 metadata service on port 80 on a special IP
    privileged: true
    ports:
      # For moto
      - "5000:5000"
      # For ec2-metadata-mock
      - "8111:8111"
  bats_ubuntu1804:
    build:
      context: ./
      dockerfile: Dockerfile.ubuntu18.04.bats
    volumes:
      # Mount all the files so you have "hot reload" of all changes from the host
      - ./:/usr/local/src/bash-commons
    working_dir: /usr/local/src/bash-commons
    command: bats test
    # Necessary so we can run a mock EC2 metadata service on port 80 on a special IP
    privileged: true
    ports:
      # For moto
      - "5000:5000"
      # For ec2-metadata-mock
      - "8111:8111"
