version: 2
jobs:
  build:
    # We need to run Docker Compose with privileged settings, which isn't supported by CircleCI's Docker executor, so
    # we have to use the machine executor instead.
    machine: true
    steps:
      - checkout
      - run: |
          cd test
          docker-compose up
