version: 2
jobs:
  shellcheck:
    machine: true
    steps:
      - checkout
      - run: docker-compose up shellcheck

  bats_ubuntu1604:
    # We need to run Docker Compose with privileged settings, which isn't supported by CircleCI's Docker executor, so
    # we have to use the machine executor instead.
    machine: true
    steps:
      - checkout
      - run: docker-compose up bats_ubuntu1604

  bats_ubuntu1804:
    # We need to run Docker Compose with privileged settings, which isn't supported by CircleCI's Docker executor, so
    # we have to use the machine executor instead.
    machine: true
    steps:
      - checkout
      - run: docker-compose up bats_ubuntu1804

workflows:
  version: 2
  checks:
    jobs:
      - shellcheck
      - bats_ubuntu1604
      - bats_ubuntu1804
